# Generated by Django 5.0.1 on 2024-02-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_options_option_rename_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_question', to='app.option'),
        ),
    ]
